# This file defines Suunto Whiteboard API for Movesense Hackathon 2016 sample
#
swagger: '2.0'

# Document metadata
info:
  version: "0.0.0"
  title: Movesense Accelerometer sample app API 
  description: |
    This file defines API for Fyysikkokilta handwaving measurement service.
  termsOfService:
  contact:
    name: Pietari Kaskela
    url: http://fyysikkokilta.fi
# Paths
paths:
  /Fyssa/Handwaving:
    get:
      description: |
        Get a Data value.
      responses:
        200:
          schema:
              description: Biggest handwave
              type: integer
              format: uint16

        204:
          description: Measurement source is unavailable

definitions:
  SampleDataValue:
    required:
      - RelativeTime
      - Value
    properties:
      RelativeTime:
        description: Relative time of measurement
        type: integer
        format: uint32
        x-unit: millisecond
      Value:
        description: Sample Data Value (in practice max absolute acceleration, over about 5 seconds when subscribed)
        type: number
        format: float
        x-unit: m/s^2
